### ISSUE TITLE
关于CNVD的反爬虫机制

### ISSUE THREAD

**Issue by wjcIvan** [hi-KK/VulDB_Spider#2]
我在跑cnvd的爬虫代码时发现无法获取到数据，后面分析了一下，是由于cnvd对cookie进行了加密，状态码为521，我还在研究怎么解密，这边跟你反馈一下。

**Comment by wjcIvan** [comment]
selenium初始化的cookie无法在requests中使用，仍需要解密cookie，在解密后二次访问该链接时，可以返回数据，但被认定为非法操作，结果还是绕不过去。

**Comment by hi-KK** [comment]
@wjcIvan 好的，感谢反馈，空下来我也去研究下现行的反爬机制
