### ISSUE TITLE
adad

### ISSUE THREAD

**Issue by XK111** [hi-KK/VulDB_Spider#4]

**Comment by hi-KK** [comment]
感谢支持，不过目前暂无时间维护最新代码，可根据现有代码思路做调整，应该不会有困难

**Comment by XK111** [comment]
我根据你的思路调整了下代码发现还是有点问题，麻烦您抽几分钟看看 毕竟你很熟悉这个，我过段时间这边有些项目，不知道你这边接不，酬劳可以谈，你有微信或者qq吗 我加你 具体私聊

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
