### ISSUE TITLE
2

### ISSUE THREAD

**Issue by CreatMusic** [hi-KK/VulDB_Spider#7]

**Comment by hi-KK** [comment]
我看是你自己没能力改代码，别在这丢人现眼了

**Comment by hi-KK** [comment]
> 我看是你自己没能力改代码，别在这丢人现眼了

@CreatMusic  怎么特地注册个小号来评论？怎么不敢拿大号来对线呢？犹如哗众取宠、跳梁小丑之辈

**Comment by CreatMusic** [comment]
> > 我看是你自己没能力改代码，别在这丢人现眼了
> 
> @CreatMusic 怎么特地注册个小号来评论？怎么不敢拿大号来对线呢？犹如哗众取宠、跳梁小丑之辈

？？？？？什么鬼?
